### ISSUE TITLE
Have next request triggered by callback from previous request

### ISSUE THREAD

**Issue by JeffML** [Foliotek/AjaxQ#14]
There may be an easy way to do this without using timers:  I want to block the next request in the queue until the previous request's callback function has finished executing.  The only way I can envision this is to block the queue on the previous request, and unblock it by having the callback call an unblockQueue() [doNextRequest()?] method on ajaxq.

**Comment by thedustinsmith** [comment]
One way we could accomplish this would be to have an option that you can pass in when queuing a request that is `autoDequeue` (true by default), and if it's set to false, we can modify the arguments that we send to the done and fail callbacks that include a `dequeue()` method.

The things I don't like about that solution is, currently, the options passed into ajaxQ are unmodified jQuery ajax options, as are the arguments passed into the callbacks.  This would add some custom methods/properties to jQuery's.
