### ISSUE TITLE
Problem In Queue

### ISSUE THREAD

**Issue by ahmedali5530** [Foliotek/AjaxQ#18]
Hi,
I m using this plugin, but my ajax requests are as usually getting cancelled.
![image](https://cloud.githubusercontent.com/assets/4495669/9540625/74aafbea-4d7a-11e5-830d-d4a2c79d9b74.png)

Thanks in Advance.

**Comment by thedustinsmith** [comment]
Without seeing any code, it's kind of hard to guess why these might be cancelled.  Are you calling `.abort()` on any of your requests?  Or calling `$.ajaxq.abort(qname)` would have this same effect if you called it in the middle of the request.
