### ISSUE TITLE
Misleading Error text

### ISSUE THREAD

**Issue by obouchari** [Foliotek/AjaxQ#24]
There is an error on line 27: 
```
if (typeof opts === "undefined") {
      throw ("AjaxQ: queue name is not provided");
}
```

I think it should say: "AjaxQ: no options provided" or something like that. because you're not testing for qname.

**Comment by siburny** [comment]
Actually, the error message here is correct. Default behavior for $.ajax is to receive an object with options. However, $.ajaxq requires a queue name in the first parameter. So when someone who worked with jQuery before tries to use ajaxq without modifying supplied parameters they will see this message.

**Comment by obouchari** [comment]
Ohh Ok, my bad
