### ISSUE TITLE
Feature request - giving delays

### ISSUE THREAD

**Issue by trante** [Foliotek/AjaxQ#3]
Thank you for great script. That's cool.

It would be helpful if we can give predefined second delays between each AJAX request.
That will give more human-like behaviour to our requests :)

**Comment by michelollivier** [comment]
Thanks,

I added delay and it works great. I queue all ajax request with predefined delay. So that, with a php controller I can set a maximum of 1 request per second per user IP. That's the way I use to stop overflooding.

`$.ajaxq = function(qname, delay, opts) {`
`...`
`enqueue(function() {
            
            //modification added settimout 1 s
            var timeout = window.setTimeout(function() {
                                
                // Send off the ajax request now that the item has been removed from the queue
                var jqXHR = $.ajax.apply(window, [deferredOpts ? opts() : clonedOptions]);
    
                // Notify the returned deferred object with the correct context when the jqXHR is done or fails
                // Note that 'always' will automatically be fired once one of these are called: http://api.jquery.com/category/deferred-object/.
                jqXHR.done(function() {
                    deferred.resolve.apply(this, arguments);
                });
                jqXHR.fail(function() {
                    deferred.reject.apply(this, arguments);
                });
    
                jqXHR.always(dequeue); // make sure to dequeue the next request AFTER the done and fail callbacks are fired
    
                return jqXHR;            
            
            } , delay);

        });`

Regards
Michel
