### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by lyudmil** [Foliotek/AjaxQ#6]
Hello again,

I felt a bit uncomfortable not having unit tests for my modifications to AjaxQ, so I set up a Jasmine standalone test runner and added tests for the code I wrote. Is this something that you'd be interested in having on the main branch? I so, I could complete the test suite, adding tests for the core functions ($.ajaxq, $.getq, $.postq) and send a pull request.

Thanks again for releasing this, it has really helped.

**Comment by jagandecapri** [comment]
@thedustinsmith @lyudmil  I have made a PR to add tests https://github.com/Foliotek/AjaxQ/pull/21

As @lyudmil  said, this library has really helped me in my work. Thought of giving back. Cheers. :)

**Comment by thedustinsmith** [comment]
Thanks for the PR @jagandecapri !

**Comment by jagandecapri** [comment]
Welcome. Thanks again for this plugin. :100:
